local Adapter = require("abcql.db.adapter.base")

describe("BaseAdapter", function()
  local adapter

  before_each(function()
    adapter = Adapter.new({ host = "localhost", port = 3306 })
  end)

  describe("new", function()
    it("should create a new adapter instance", function()
      assert.is_not_nil(adapter)
      assert.is_table(adapter.config)
    end)

    it("should store config", function()
      assert.are.equal("localhost", adapter.config.host)
      assert.are.equal(3306, adapter.config.port)
    end)

    it("should handle nil config", function()
      local adapter_no_config = Adapter.new()
      assert.is_not_nil(adapter_no_config)
      assert.is_table(adapter_no_config.config)
    end)

    it("should handle empty config", function()
      local adapter_empty = Adapter.new({})
      assert.is_not_nil(adapter_empty)
      assert.is_table(adapter_empty.config)
    end)
  end)

  describe("abstract methods", function()
    it("get_command should throw error", function()
      assert.has_error(function()
        adapter:get_command()
      end, "get_command must be implemented by adapter")
    end)

    it("get_args should throw error", function()
      assert.has_error(function()
        adapter:get_args("SELECT 1")
      end, "get_args must be implemented by adapter")
    end)

    it("parse_output should throw error", function()
      assert.has_error(function()
        adapter:parse_output("some output")
      end, "parse_output must be implemented by adapter")
    end)

    it("get_databases should throw error", function()
      assert.has_error(function()
        adapter:get_databases(function() end)
      end, "get_databases must be implemented by adapter")
    end)

    it("get_tables should throw error", function()
      assert.has_error(function()
        adapter:get_tables("mydb", function() end)
      end, "get_tables must be implemented by adapter")
    end)

    it("get_columns should throw error", function()
      assert.has_error(function()
        adapter:get_columns("mydb", "mytable", function() end)
      end, "get_columns must be implemented by adapter")
    end)
  end)

  describe("default implementations", function()
    describe("escape_identifier", function()
      it("should return unmodified identifier", function()
        local result = adapter:escape_identifier("table_name")
        assert.are.equal("table_name", result)
      end)

      it("should not escape special characters by default", function()
        local result = adapter:escape_identifier("table-with-dashes")
        assert.are.equal("table-with-dashes", result)
      end)
    end)

    describe("escape_value", function()
      it("should return unmodified value", function()
        local result = adapter:escape_value("some value")
        assert.are.equal("some value", result)
      end)

      it("should not escape quotes by default", function()
        local result = adapter:escape_value("value with 'quotes'")
        assert.are.equal("value with 'quotes'", result)
      end)
    end)
  end)
end)
